### ISSUE TITLE
Inconsistent FrameLink::initializeUsingXML and FrameLink XML schema

### ISSUE THREAD

**Issue by friedrichatgc** [mbsim-env/mbsim#41]
FrameLink::initializeUsingXML reads a `<mbsim:connect ref1=... ref2=.../>` element but this element is not defined in the FrameLink XML schema, its defined in the SpringDamper XML schema. This is a bug.

This makes it currently impossible to derive from FrameLink in a MBSim module (other then kernel), because one cannot define a `<mbsim:connect>` element in a XML schema of a module (you can only defined elements is the namespace of the current schema but not in another namespace).

However, `<mbsim:connect>` is not the first element in SpringDamper. Hence, this element cannot be moved to FrameLink without breaking compatibility of XML input files. But since this is a bug we need to go this way and move it to FrameLink and fix all examples.

The same applies for the `<enableOpenMBVForce>` element in FrameLink/SpringDamper.

**Comment by foerg** [comment]
This seems to be a bug. Another solution would be to remove the connect memberfunction from FrameLink, but this is more like a workaround. So the proper solution is to move the <mbsim:connect> element to FrameLink and fix all examples.

**Comment by friedrichatgc** [comment]
Fixed
