### ISSUE TITLE
How to get an XY plot of some variables

### ISSUE THREAD

**Issue by ManuelZ** [mbsim-env/mbsim#46]
I'd like to plot some variables in an XY plot, but I've not been able to achieve this so far. How do I do this?

Thanks

**Comment by foerg** [comment]
First, choose the y data by a left mouse click. Then select the "x-Label" in the tab view. Finally, choose the x data by shift an left mouse click. Alternatively, you can export the data to an hdf5 file and do the post processing e.g. within Matlab.
