### ISSUE TITLE
Possible export of a MBSim model on an external hardware

### ISSUE THREAD

**Issue by ga53hon** [mbsim-env/mbsim#48]
Dear developers,

I would like to export the model to an external hardware to analyze the possbility to further accelerate the model execution. At the moment I am familiar with the FMU-export for Simulink, which works pretty well. However, it is not possible to use the FMU on an external hardware. 
Therefore my question: would it be possible to export the model in any other format? My first trial would be to run the model on a GPU.

Thank you very much in advance 
Best regards
Francesco Passigato

**Comment by friedrichatgc** [comment]
Hi Francesco,
the FMU-export of MBSim works in all tools which are able to import FMI 1.0. See https://fmi-standard.org/tools/ for a list of tools. MBSim supports FMI 1.0 export for Co-Simulation and Model-Exchange. However, this works only for the two supported platform of MBSim: win64 and linux64.
The only other way to export the model is a linearized model export as state-space-representation: ABCD matrices. Use the LinearSystemAnalyzer analyzer for this (https://www.mbsim-env.de/static/runtime/xmlReference/http___www_mbsim-env_de_MBSimControl/index.html#LinearSystemAnalyzer)
"Exporting" the non-linear model to a GPU is not possible by MBSim. I my view multi-body-systems are even not well suited for GPU computing.
