### ISSUE TITLE
Multiple dynamics after another and not simultaneously

### ISSUE THREAD

**Issue by Jantsche** [mbsim-env/mbsim#49]
Hello,
Ive been using MBSim to work on a semester project. One of the tasks is to give a short but efficient tutorial of the software.
For that i have decided to use a simulation of a bouncing ball on a declined plane in three variants. The first is only with a point on the ball to just get the jumping. The second is a circle that jumps on the plane and the third is a full ball contour. The last two ones are also set under friction.
Here I noticed that the ball initially bounces and only after the complete decay of these jumps the friction brings the ball to roll.
Realistically the ball should get a rotation as soon as the first contact occurs.
In another test, the ball was subjected to an initial rotation to the side and then dropped, but here, too, the bouncing subsides first, before a deflection to the side occurs.
Ive been quite stuck at this problem for a while. Maybe i did something wrong.

**Comment by foerg** [comment]
Hi,
be sure that you also define a tangential impact law with the proper friction coefficient. This way the ball gets an impulsive force in tangential direction which leads to an instantaneous increase of the angular velocity om. If the friction coefficient is high enough you should get an angular velocity comparable to pure rolling right after the first impact. 
An exemplary implementation is attached below.
[MBS.mbsx.zip](https://github.com/mbsim-env/mbsim/files/11478459/MBS.mbsx.zip)

**Comment by Jantsche** [comment]
Hello,
I have defined a tangential impact law and used an initial velocity in z direction but now the ball only rotates around the z-axis. 
I would expect the ball to also get a rotation around the x/y- axis.
I have attached an example.

[springender_Ball_schiefe_Ebene.zip](https://github.com/mbsim-env/mbsim/files/11532236/springender_Ball_schiefe_Ebene.zip)

Thanks for the fast reply.

**Comment by foerg** [comment]
For motions in 3D you have to switch to "spatial coulomb friction" and "spatial coulomb impact". The modified model file is attached below.
[springender_Ball_schiefe_Ebene_mod.mbsx.zip](https://github.com/mbsim-env/mbsim/files/11532414/springender_Ball_schiefe_Ebene_mod.mbsx.zip)

**Comment by Jantsche** [comment]
Ah i must have missed that. Thank u very much for the correction.
