### ISSUE TITLE
Be member of Calculix group at github?

### ISSUE THREAD

**Issue by stefano2734** [mbsim-env/mbsim#51]
So more users see, that MBsim can use Calculix.

see https://github.com/calculix

And Calculix in search words of the GitHub project page to find mbsim in search for Calculix is also an idea.

**Comment by foerg** [comment]
Connecting the two projects is generally a good idea. However, I can't find the source code of CaluliX at https://github.com/calculix. What is the connection to the Github page https://github.com/Dhondtguido/CalculiX?

**Comment by foerg** [comment]
Thank you for the explanation. We can of course establish a connection between the two projects. If you want, we can create a link to CalculiX in the MBSim topics.

**Comment by stefano2734** [comment]
Yes, that is ok. 
In „About“ at GitHub of mbsim you can add „calculix“ to other words for better search.

Being a member of calculix organization is quite simple and with no work.
see
https://github.com/calculix/.github/blob/main/profile/README.md

**Comment by friedrichatgc** [comment]
I have now added the 4 "Used (Quasi)-Standards" (fmi, hdf5, calculix, pacejka) from the MBSim homepage as topics keywords to the mbsim repo.
