### ISSUE TITLE
Use Generalized Force Sensor output as input for Kinetic Excitation

### ISSUE THREAD

**Issue by AS-1108** [mbsim-env/mbsim#53]
Hello,

for my current project I'd need to take the signal output of a Generalized Force Sensor, do some calculations with it in a Signal Operation link and then use the resulting signal as an input for a Kinetic Excitation. This leads to an algebraic loop, though, which doesn't let the simulation work. I'd like to know if there's some kind of delay I can use inbetween the Signal Operation and the Kinetic Excitation to resolve this problem.

Thanks in advance for your help and for maintaining this great software!

**Comment by foerg** [comment]
Hi,
there are two ways to solve this problem:
1. Use a PT1 element for the delay. An implementation can be found here: https://github.com/mbsim-env/mbsim/blob/master/models/control/PT1.mbsmx
2. Regularize the force law of the mechanical link the generalized force sensor is connected to.
Hope this helps.

**Comment by AS-1108** [comment]
Hello,

using the PT1 element works for me, thanks for your help!
